Update Breaker show link rule
nathangathright/podcast-platform-links pull request #4
Opened 2021-08-27 09:29 UTC by sinchang

2021-08-30 21:24 UTC, nathangathright commented on README.md
> +* Breaker: `https://breaker.audio/${slug}`
```suggestion
* Breaker: `https://breaker.audio/${uniquePlatformID}`
```

For the purposes of this document, `slug` is defined as a string with a malleable, arbitrary value. `uniquePlatformID` is the correct term.

2021-08-30 21:25 UTC, nathangathright requested changes
For the purposes of this document, `slug` is defined as a string with a malleable, arbitrary value. `uniquePlatformID` is the correct term.

2021-08-30 21:25 UTC, nathangathright commented on README.md
> +* Breaker: `https://breaker.audio/${slug}/e/${uniqueEpisodeID}`
```suggestion
* Breaker: `https://breaker.audio/${uniquePlatformID}/e/${uniqueEpisodeID}`
```

2021-08-30 21:27 UTC, nathangathright commented
I've spoken with Greg Wasserman at Maple Media, owner of Breaker, and he's provided this statement:
> Yes we are aware and sorry for the confusion, we are in the process of taking that page down, and if you have a show you want to submit or update on Breaker, please contact support and include the RSS feed. Support can be reached at feedback@breaker.audio

2021-08-31 01:46 UTC, sinchang commented
@nathangathright thanks for the clarification.

2021-08-31 04:09 UTC, merged